# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
common: &common
  adapter: postgresql
  username:
  password:
  host: localhost
  timeout: 5000

development:
  <<: *common
  database: new_sweet_articles_dev

test:
  <<: *common
  database: new_sweet_articles_test

production:
  <<: *common
  database: new_sweet_articles
